export const ERROR_CODES = {
  NO_AUTORIZADO: 'NO_AUTORIZADO',
  ERROR_INTERNO: 'ERROR_INTERNO',
  NO_ENCONTRADO: 'NO_ENCONTRADO',
  NOMBRE_INVALIDO: 'NOMBRE_INVALIDO',
  NUMERO_INVALIDO: 'NUMERO_INVALIDO',
} as const;
