export const PRODUCTO_ERROR_CODES = {
  STOCK_INVALIDO: 'STOCK_INVALIDO',
  PRECIO_INVALIDO: 'PRECIO_INVALIDO',
  DISPONIBILIDAD_INVALIDA: 'DISPONIBILIDAD_INVALIDA',
  PRODUCTO_EN_RESERVA: 'PRODUCTO_EN_RESERVA',
  PRODUCTO_YA_EXISTE: 'PRODUCTO_YA_EXISTE',
  STOCK_INSUFICIENTE: 'STOCK_INSUFICIENTE',
} as const;
